# language: haskell

sudo: required

env:
 - GHCVER=7.10.3 CABALVER=1.24
 - GHCVER=8.0.2 CABALVER=1.24
 - GHCVER=8.2.2 CABALVER=1.24
 - GHCVER=7.10.3 CABALVER=2.0
 - GHCVER=8.0.2 CABALVER=2.0
 - GHCVER=8.2.2 CABALVER=2.0
 - GHCVER=8.4.1 CABALVER=2.0
 
before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install hoogle cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal update

 # These sandbox commands are doing manually what mafia would do when building itself.
 - cabal sandbox init

script:
 - cabal install --dependencies-only --enable-tests
 - cabal configure --enable-tests
 - cabal build
 - dist/build/test/test
 - dist/build/test-io/test-io
 - dist/build/test-cli/test-cli
 - cabal haddock
 - 'if [ ${CABALVER} = "2.0" ]; then
      cabal sdist ;
    fi'
