#!/bin/sh -eu

usage () {
    status=${1:-0}
    cat <<EOF
./cabal [command] [options]

Commands:
    build           Build this project, including all executables and test suites.
    test            Test this project, by default this runs all test suites.
    repl            Start the repl, by default on the the main library source.
    quick           Start the repl directly skipping cabal, this is useful developing
                    across multiple source trees at once.
    watch           Watches filesystem for changes and stays running, compiles and gives quick feedback.
                    Similarly to quick needs an entrypoint.
    demo            If this project has a demo application, this builds and runs it.
    exec            If this project has an executable, this builds and runs it.
    tags            Generate tags for this project.
    lint            Lint the project.
    init            Start a new project.
    update          Cabal update, but limited to retrieving at most once per day.
    clean           Remove compiled artifacts.
    depend          Dependency organisation tooling check|deep-check|sync.
EOF
    exit ${status}
}

fail () {
     message="${1:-}"
     [ -z "$message" ] || echo "${message}" 1>&2
     usage 1 1>&2
}


#
# Determine the project name from the cabal file.
#
project_name () {
    find . -maxdepth 1 -name  \*.cabal -type f | xargs basename | sed -e 's/.cabal//'
}

#
# Initialize things for a build. This can be made faster by being
# a lot smarter about doing things conditionally, but for now,
# brute force wins.
#
initialize () {
    # sandbox has all sources
    project=$(project_name)
    SANDBOX_DIR=.cabal-sandbox
    [ ! -f "${project}.sandbox" ] || {
        SANDBOX_DIR=$(cat ${project}.sandbox)
        SANDBOX="--sandbox ${SANDBOX_DIR}"
    }

    # sandbox initialized if required, this should support sandboxes in parent directories
    [ -f cabal.sandbox.config ] || {
        cabal sandbox ${SANDBOX:-} init
    }

    [ ! -f "$project.submodules" ] || {
        # submodules initialized if required, the "has it been done before" is pretty crude, but check is useful.
        cat $project.submodules | while read submodule; do
            if [ -d "$submodule" ]; then
               find "$submodule" -maxdepth 2 -name \*.cabal
            fi
        done | grep -q . || (
            cd $(git rev-parse --show-toplevel)
            git submodule init
            git submodule update
        )

        cat $project.submodules | while read submodule; do
            if ! grep -q "${submodule}\"" ${SANDBOX_DIR}/add-source-timestamps; then
                cabal sandbox add-source ${SANDBOX:-} "$submodule"
            fi
        done
    }

    # all dependencies installed, and configure been run?
    cabal install -j --only-dependencies --force-reinstalls --enable-tests
    cabal configure --enable-tests
}

#
# Cabal build.
#
run_build () {
    initialize
    cabal build --ghc-option="-Werror"
}

#
# Cabal test.
#
run_test () {
    initialize
    cabal test "$@"
}

#
# Cabal repl.
#
run_repl () {
    initialize
    cabal repl "$@"
}

#
# Load up the repl in "quick" mode.
#
run_quick () {
    initialize
    [ $# -eq 1 ] || fail "'quick' requires a single argument, specifying the entry point you want to load."
    [ -f "$1" ] || fail "The entry point does not exist."
    [ ! -d src ] || SRC_DIRS="-isrc"
    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
    ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} "$1"
}

#
# Load up ghcid
#
run_watch () {
    command -v ghcid >/dev/null 2>&1 || { echo >&2 "ghcid required not installed. To install: create a fresh cabal sandbox, cabal install ghcid and add to your \$PATH."; exit 1; }
    initialize
    [ $# -eq 1 ] || fail "Watch requires a single argument, specifying the entry point you want to load."
    [ -f "$1" ] || fail "The entry point does not exist."
    [ ! -d src ] || SRC_DIRS="-isrc"
    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
    ghcid -c "ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} \"$1\""
}

#
# Remove compiled artifacts.
#
run_clean () {
    cabal clean
}

#
# Dependency tools.
#

# using this instead of git submodule foreach in the hope I can avoid recursive submodule init/updates (probably can't though, so this may be irrelevant).
list_modules () {
    [ $# -eq 1 ] || fail "list_modules requires a single argument, specifying the root of the project."
    MODULES="$1/.gitmodules"
    if [ -f "${MODULES}" ]; then
        grep path "${MODULES}" | sed 's/.*= //'
    fi
}

force_sync () {
    [ $# -eq 1 ] || fail "force sync requires a single argument, specifying the root of the project."
    SYNC_ROOT="$1"
    (
        cd "${SYNC_ROOT}" ## required for submodule commands on older versions of git
        git fetch
        git submodule init
        git submodule update
        git submodule sync
    ) > /dev/null 2>&1
}

run_depend_check () {
    TOP=$(git rev-parse --show-toplevel)
    force_sync "${TOP}"
    list_modules "${TOP}" | while read SUBMODULE; do
        (
            cd "${TOP}/${SUBMODULE}"
            echo "$SUBMODULE"
            git fetch > /dev/null 2>&1
            OUT=$(git rev-list --left-right --count origin/master...)
            BEHIND=$(echo $OUT | awk '{ print $1 }')
            AHEAD=$(echo $OUT | awk '{ print $2 }')

            if [ "$AHEAD" -eq 0 -a "$BEHIND" -eq 0 ]; then
                echo '  `- [OK]'
            elif [ "$AHEAD" -eq 0 -a "$BEHIND" -gt 0 ]; then
                echo '  `- [WARNING] Behind master.'
            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -eq 0 ]; then
                echo '  `- [WARNING] Commits not on master.'
            elif [ "$AHEAD" -gt 0 -a "$BEHIND" -gt 0 ]; then
                echo '  `- [WARNING] Commits not on master & behind master.'
            fi
        )
    done
}

run_depend_deep_check () {
    TOP=$(git rev-parse --show-toplevel)
    force_sync "${TOP}"
    list_modules "${TOP}" | while read SUBMODULE; do
        (
            echo "$SUBMODULE"
            force_sync "${TOP}/${SUBMODULE}"
            list_modules "${TOP}/${SUBMODULE}" | while read SUBSUBMODULE; do
                if [ -e "${TOP}/${SUBSUBMODULE}" ]; then
                    NESTED=$(cd "${TOP}/${SUBMODULE}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
                    OUTER=$(cd "${TOP}/${SUBSUBMODULE}" > /dev/null 2>&1; git rev-parse HEAD);
                    if [ "${NESTED}" = "${OUTER}" ]; then
                        echo "  \`- [OK] ${SUBSUBMODULE}"
                    else
                        (
                            cd "${TOP}/${SUBSUBMODULE}"
                            git fetch > /dev/null 2>&1
                            echo ${TOP}/${SUBSUBMODULE}
                            OUT=$(git rev-list --left-right --count "${NESTED}...${OUTER}")
                            BEHIND=$(echo $OUT | awk '{ print $1 }')
                            AHEAD=$(echo $OUT | awk '{ print $2 }')
                            echo "  \`- [WARNING] ${SUBSUBMODULE} is out of sync, outer commit ${OUTER}, nested ${NESTED}, outer is ${BEHIND} commits behind, ${AHEAD} commits ahead."
                        )
                    fi
                else
                    echo "  \`- [WARNING] Potentially missing dependency ${SUBSUBMODULE}"
                fi
            done
        )
    done
}

run_depend_sync () {
    TOP=$(git rev-parse --show-toplevel)
    list_modules "${TOP}" | while read SUBMODULE; do
        (
            echo "$SUBMODULE"
            force_sync "${TOP}/${SUBMODULE}"

            cd "${TOP}/${SUBMODULE}"
            if git branch -a | grep -q origin/ambiata; then
                git checkout ambiata
                git merge origin/ambiata
            else
                git checkout master
                git merge origin/master
            fi

            force_sync "${TOP}/${SUBMODULE}"
        )
    done
}

run_depend () {
    [ $# -eq 1 ] || fail "'depend' requires a single argument, specifying the mode as one of [check|deep-check|sync]."

    case "$1" in
    check) run_depend_check ;;
    deep-check) run_depend_deep_check ;;
    sync) run_depend_sync;;
    *) fail "Unknown mode [$1], expected one of [check|deep-check|sync]" ;;
    esac
}

#
# Run hasktags on this project.
#
run_tags () {
    # TODO should install hasktags if it doesn't exist yet.
    hasktags -e src test main
}

#
# Run hlint on this project (building hlint if necessary).
#
run_lint () {
    # TODO should install hlint if it doesn't exist yet.
    hlint src test main
}

#
# Run cabal update, but not more often than once a day.
#
run_update () {
    if ! test -f $HOME/.cabal/packages/hackage.haskell.org/00-index.cache || find $HOME/.cabal/packages/hackage.haskell.org/00-index.cache -type f -mtime +1 | grep -q 00-index; then
        cabal update
    else
        true
    fi
}


#
# The actual start of the script.....
#


[ $# -gt 0 ] || fail

case "$1" in
-h|--help) usage ;;
esac

MODE="$1"; shift
case "$MODE" in
build|test|repl|quick|tags|lint|update|clean|depend|watch) run_$MODE "$@" ;;
*) fail "Unknown mode: $MODE"
esac
