#!/bin/sh -eux

absolute_path() {
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

MAFIA=$(absolute_path ${1:-./dist/build/mafia/mafia})

${MAFIA} -v
${MAFIA} --version

${MAFIA} -h
${MAFIA} --help

MAFIA_TEMP=$(mktemp -d 2>/dev/null || mktemp -d -t 'mafia')
trap "rm -rf \"${MAFIA_TEMP}\"" EXIT

check() {
  MAFIA_REPO=$1
  MAFIA_DIR=$2
  MAFIA_ENTRY=$3

  cd ${MAFIA_TEMP}
  if [ ! -d "${MAFIA_REPO}" ]; then
    git clone https://github.com/ambiata/${MAFIA_REPO}
  fi

  cd ${MAFIA_DIR}
  MAFIA_HOME=${MAFIA_TEMP} ${MAFIA} build
  MAFIA_HOME=${MAFIA_TEMP} ${MAFIA} build
  MAFIA_HOME=${MAFIA_TEMP} ${MAFIA} quick ${MAFIA_ENTRY} <<EOF
    :q
EOF
}

check p p           src/P.hs
check x x/x-eithert src/X/Control/Monad/Trans/Either.hs
check x x/x-conduit src/X/Data/Conduit/Binary.hs
